version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment-app
    depends_on:
      - db
    container_name: payment-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .env:/var/www/html/.env
    environment:
      - "APP_NAME=${APP_NAME}"
      - "APP_ENV=${APP_ENV}"
      - "APP_DEBUG=${APP_DEBUG}"
      - "APP_URL=${APP_URL}"
      - "DB_CONNECTION=${DB_CONNECTION}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8090:8090"

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    command: [ '--bind-address=0.0.0.0' ]
